# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

build:
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq make
    - cd src/utils && make
    # - cd ../devices/
    # - make
    # - cd build
    # - make check
    # - cd ../../threads
    # - make
    # - cd build
    # - make check
