stages:
    - build
    - test

build:
    stage: build
    only:
        - master
    script:
        - cd src/utils && make
        - export PATH=".:$PATH"
        - cd ../devices && make
        - cd ../threads && make
        - cd ..
testsuite:
    stage: test
    only:
        - master
    script:
        - cd devices/build/
        - make check
