stages:
    - build
    - test

build:
    stage: build
    only:
        - master
    script:
        - cd src/utils && make
        - export PATH=".:$PATH"
        - cd ../devices && make
        - cd ../threads && make
        - cd ..

testsuite:
    stage: test
    only:
        - master
    script:
        # - apt-get install -y qemu
        - cd src/utils && make
        - export PATH=$(pwd):$PATH
        - cd ../devices && make
        - cd ../devices/build/
        - make check
